name: Docker Image CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ all ]
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          cp .env.example .env
          docker-compose build
